/*
 * Vencord, a modification for Discord's desktop app
 * Copyright (c) 2023 Vendicated and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/*
 * All texts of the plugin, Russian and English. Any other language is translated from the English text
 * (see i18n.ts). In a text, {name} marks a place filled in by the program.
 */

export const TEXTS = {
    modalFallbackTitle: { ru: "Этот чат", en: "This chat" },
    incoming: { ru: "Входящие сообщения", en: "Incoming messages" },
    autoRead: { ru: "Автоперевод чата", en: "Auto-translate chat" },
    autoReadDesc: { ru: "Все входящие сообщения этого чата переводятся сами, по мере появления на экране.", en: "All incoming messages in this chat are translated automatically as they appear on screen." },
    autoReadMore: { ru: "Пропускает сообщения на твоём языке и те, где ты отключил перевод.", en: "Skips messages that are already in your language and those you turned translation off for." },
    chatLanguage: { ru: "Язык чата", en: "Chat language" },
    translateChatTo: { ru: "Переводить чат на", en: "Translate chat to" },
    outgoing: { ru: "Исходящие сообщения", en: "Outgoing messages" },
    translateMine: { ru: "Переводить мои сообщения", en: "Translate my messages" },
    translateMineDesc: { ru: "Перед отправкой твой текст переводится на язык ниже.", en: "Before sending, your text is translated into the language below." },
    originalMine: { ru: "Оригинал моих сообщений", en: "Original of my messages" },
    originalMineDesc: { ru: "Твои сообщения в чате видны на твоём языке, а собеседники видят перевод.", en: "Your messages appear in your language to you, while others see the translation." },
    originalMineMore: { ru: "Тексты берутся из того, что запомнено при отправке. Работает, только пока включено «Переводить мои сообщения».", en: "Texts are taken from what was remembered when sending. Works only while “Translate my messages” is on." },
    myLanguage: { ru: "Язык моих сообщений", en: "Language of my messages" },
    translateMineTo: { ru: "Переводить мои сообщения на", en: "Translate my messages to" },
    openFullSettings: { ru: "Открыть полный список настроек", en: "Open the full list of settings" },
    detectLanguage: { ru: "Определить язык", en: "Detect language" },
    pickLanguage: { ru: "Выбери язык", en: "Choose a language" },
    settingsTitle: { ru: "Настройки", en: "Settings" },
    thisServer: { ru: "Этот сервер", en: "This server" },
    directMessages: { ru: "личные сообщения", en: "direct messages" },
    serverSend: { ru: "Переводить мои сообщения на всём сервере", en: "Translate my messages on the whole server" },
    serverSendDesc: { ru: "Включает перевод во всех чатах сервера.", en: "Turns translation on in all chats of the server." },
    serverSendMore: { ru: "Личные настройки чатов сервера сбрасываются, потом любой чат меняется отдельно.", en: "Personal settings of the server's chats are reset; afterwards any chat can be changed separately." },
    serverLanguage: { ru: "Язык моих сообщений на сервере", en: "Language of my messages on the server" },
    ownDelay: { ru: "Задержка для моих сообщений", en: "Delay for my messages" },
    ownDelayDesc: { ru: "Сколько секунд видно отправленный вариант перед переводом.", en: "How many seconds the sent version stays visible before the change." },
    sentTip: { ru: "Подсказка «переведено»", en: "“Translated” tip" },
    sentTipDesc: { ru: "У кнопки чата на 2 секунды после отправки переведённого сообщения.", en: "Shown at the chat button for 2 seconds after a translated message is sent." },
    enterDelay: { ru: "Задержка автоперевода при входе в чат", en: "Auto-translate delay when entering a chat" },
    enterDelayDesc: { ru: "Сколько секунд ждать после входа в чат, прежде чем переводить.", en: "How many seconds to wait after entering a chat before translating." },
    enterDelayMore: { ru: "Если за это время ты ушёл в другой чат, перевод не запускается и переводчик не нагружается. Уже переведённые сообщения показываются сразу. Клик по «Авто · ждёт» на панели пропускает ожидание.", en: "If you moved to another chat in the meantime, translation does not start and the translator is not loaded. Already translated messages appear at once. A click on “Auto · waiting” on the panel skips the wait." },
    ahead: { ru: "Сколько сообщений переводить за экраном", en: "How many messages to translate beyond the screen" },
    aheadDesc: { ru: "Запас выше и ниже видимой части чата.", en: "A reserve above and below the visible part of the chat." },
    aheadMore: { ru: "Больше — плавнее при прокрутке, но больше работы для переводчика.", en: "More means smoother scrolling but more work for the translator." },
    nothingToTranslate: { ru: "Здесь нечего переводить: текст уже на твоём языке или в нём нет слов.", en: "Nothing to translate here: the text is already in your language or has no words." },
    fastScroll: { ru: "Быстрая прокрутка", en: "Fast scrolling" },
    fastScrollDesc: { ru: "Если листаешь чат быстрее этой скорости, новые переводы ждут, пока прокрутка не остановится.", en: "If you scroll the chat faster than this speed, new translations wait until scrolling stops." },
    fastScrollMore: { ru: "Скорость считается в экранах чата за секунду. Чем меньше значение, тем раньше прокрутка считается быстрой и тем меньше нагрузка на компьютер. Уже переведённые сообщения подменяются как обычно.", en: "Speed is measured in chat screens per second. The lower the value, the sooner scrolling counts as fast and the lighter the load on your computer. Messages that are already translated are swapped in as usual." },
    scrollSettle: { ru: "Задержка перевода после прокрутки", en: "Translation delay after scrolling" },
    scrollSettleDesc: { ru: "Сколько секунд ждать после остановки быстрой прокрутки, прежде чем переводить.", en: "How many seconds to wait after fast scrolling stops before translating." },
    unitScreensSec: { ru: "экр./сек", en: "screens/sec" },
    idle: { ru: "Пауза автоперевода при бездействии", en: "Auto-translate pause when idle" },
    idleDesc: { ru: "Через сколько минут без мыши и клавиатуры автоперевод встаёт на паузу.", en: "After how many minutes without mouse or keyboard auto-translate pauses." },
    hiddenDelay: { ru: "Пауза при сворачивании Discord", en: "Pause when Discord is minimized" },
    hiddenDelayDesc: { ru: "Через сколько секунд после сворачивания автоперевод встаёт на паузу. 0 — сразу.", en: "After how many seconds of being minimized auto-translate pauses. 0 means at once." },
    editing: { ru: "Редактирование", en: "Editing" },
    editRemember: { ru: "Правка на своём языке", en: "Edit in your own language" },
    editRememberDesc: { ru: "«Редактировать» открывает твой исходный текст, после правки он переводится заново.", en: "“Edit” opens your original text; after editing it is translated again." },
    editRememberMore: { ru: "Хранятся последние 500 сообщений, только на этом компьютере. Если выключить, сохранённое не стирается.", en: "The last 500 messages are kept, on this computer only. Turning it off does not erase what is saved." },
    editBack: { ru: "Обратный перевод для старых", en: "Back-translation for old messages" },
    editBackDesc: { ru: "Если исходника нет, откроется перевод обратно на твой язык.", en: "If there is no original, the translation is translated back into your language." },
    editBackMore: { ru: "Это сообщения, отправленные раньше или с телефона. Чуть менее точно, поле открывается через полсекунды.", en: "These are messages sent earlier or from a phone. Slightly less exact; the field opens after half a second." },
    clearSaved: { ru: "Очистить сохранённые тексты", en: "Clear saved texts" },
    cleared: { ru: "Удалено ✓", en: "Deleted ✓" },
    memory: { ru: "Память", en: "Memory" },
    cacheSize: { ru: "Размер кэша переводов", en: "Translation cache size" },
    cacheSizeDesc: { ru: "Сколько переведённых текстов помнить, чтобы они возвращались мгновенно.", en: "How many translated texts to remember so that they come back instantly." },
    cacheSizeMore: { ru: "Кэш сбрасывается при перезапуске Discord.", en: "The cache is cleared when Discord restarts." },
    sentBuffer: { ru: "Размер буфера отправленных", en: "Sent messages buffer size" },
    sentBufferDesc: { ru: "Сколько твоих отправленных сообщений помнить для редактирования.", en: "How many of your sent messages to remember for editing." },
    imagesScreen: { ru: "Картинки и экран", en: "Pictures and screen" },
    imageMin: { ru: "Мелкий текст — открывать крупно", en: "Small text: open large" },
    imageMinDesc: { ru: "Если текст на превью мельче этого, картинка открывается большой.", en: "If the text in the preview is smaller than this, the picture opens large." },
    screenFont: { ru: "Минимальный шрифт перевода", en: "Minimum translation font size" },
    screenFontDesc: { ru: "Мельче этого перевод в плашках не ужимается.", en: "The translation in patches is not shrunk below this." },
    interface: { ru: "Интерфейс", en: "Interface" },
    hoverTips: { ru: "Подсказки при наведении", en: "Hover tips" },
    hoverTipsDesc: { ru: "Подсказка на переведённом тексте: как переключать, горячие клавиши.", en: "A tip on translated text: how to switch it, hotkeys." },
    translator: { ru: "Переводчик", en: "Translator" },
    service: { ru: "Сервис", en: "Service" },
    serviceDesc: { ru: "Google работает без ключа, DeepL и Kagi требуют ключ.", en: "Google works without a key; DeepL and Kagi require a key." },
    serviceMore: { ru: "При смене сбрасываются языки, выбранные для чатов и серверов.", en: "Changing it resets the languages chosen for chats and servers." },
    deeplKey: { ru: "Ключ DeepL (deepl.com/your-account)", en: "DeepL key (deepl.com/your-account)" },
    keyPlaceholder: { ru: "ключ", en: "key" },
    kagiToken: { ru: "Токен Kagi (kagi.com/settings?p=user_details)", en: "Kagi token (kagi.com/settings?p=user_details)" },
    tokenPlaceholder: { ru: "токен", en: "token" },
    hotkeys: { ru: "Горячие клавиши", en: "Hotkeys" },
    pressKey: { ru: "нажми клавишу", en: "press a key" },
    onlyLetterOrDigit: { ru: "Можно выбрать только букву или цифру.", en: "Only a letter or a digit can be chosen." },
    hotkeyTaken: { ru: "Alt+{key} уже занято: {action}", en: "Alt+{key} is already taken: {action}" },
    holdAltNote: { ru: "Зажать Alt: пока удерживается, показывает оригинал переведённых сообщений. Эта клавиша не настраивается.", en: "Hold Alt: shows the original of translated messages while held. This key cannot be changed." },
    resetHotkeys: { ru: "Сбросить", en: "Reset" },
    resetSection: { ru: "Сброс настроек", en: "Reset settings" },
    resetDefaults: { ru: "Настройки по умолчанию", en: "Default settings" },
    resetSure: { ru: "Нажми ещё раз, чтобы сбросить", en: "Press again to reset" },
    descMore: { ru: "▾ подробнее", en: "▾ more" },
    descLess: { ru: "▴ свернуть", en: "▴ less" },
    unitSec: { ru: "с", en: "s" },
    unitPcs: { ru: "шт", en: "pcs" },
    unitMin: { ru: "мин", en: "min" },
    hkArea: { ru: "Выделение области экрана для перевода (текст, картинки, файлы)", en: "Select a screen area to translate (text, pictures, files)" },
    hkChat: { ru: "Перевод всех видимых сообщений чата", en: "Translate all visible messages of the chat" },
    hkToggle: { ru: "Переключатель переведённых сообщений: оригинал / перевод", en: "Switch translated messages: original / translation" },
    hkReset: { ru: "Сброс переводов (не работает при включённом автопереводе)", en: "Reset translations (does not work while auto-translate is on)" },
    hkAuto: { ru: "Вкл/выкл автоперевод этого чата", en: "Turn auto-translate of this chat on/off" },
    hkListTitle: { ru: "Список горячих клавиш", en: "List of hotkeys" },
    holdAlt: { ru: "Зажать Alt", en: "Hold Alt" },
    holdAltDesc: { ru: "Пока удерживается, показывает оригинал переведённых сообщений", en: "While held, shows the original of translated messages" },
    hkConfigure: { ru: "Настроить горячие клавиши", en: "Configure hotkeys" },
    resetUnavailable: { ru: "В режиме автоперевода сброс недоступен. Чтобы вернуть оригиналы, выключи автоперевод чата (клик по «Авто → …» на панели или Alt+R).", en: "Reset is not available in auto-translate mode. To get the originals back, turn auto-translate of the chat off (click “Auto → …” on the panel or press {key})." },
    autoLabel: { ru: "Авто", en: "Auto" },
    autoNoConnection: { ru: "Авто → Нет связи", en: "Auto → No connection" },
    autoNoConnectionTip: { ru: "Переводчик не отвечает. Перевод подхватится сам", en: "The translator is not responding. Translation will resume by itself" },
    autoPaused: { ru: "Авто → Пауза", en: "Auto → Paused" },
    autoPausedTip: { ru: "Автоперевод на паузе, возобновится сам", en: "Auto-translate is paused and will resume by itself" },
    autoActive: { ru: "Авто → {lang}", en: "Auto → {lang}" },
    autoActiveTip: { ru: "Автоперевод этого чата. Клик — выключить", en: "Auto-translate of this chat. Click to turn off" },
    autoOnNote: { ru: "Автоперевод этого чата включён", en: "Auto-translate of this chat is on" },
    autoOffNote: { ru: "Автоперевод этого чата выключен", en: "Auto-translate of this chat is off" },
    roAreaTip: { ru: "Перевести текст с области экрана ({key})", en: "Translate text from a screen area ({key})" },
    roChat: { ru: "Перевод этого чата", en: "Translation of this chat" },
    panelTranslated: { ru: "Переведено", en: "Translated" },
    tipChatOn: { ru: "Автоперевод в этом чате: ВКЛ", en: "Auto-translate in this chat: ON" },
    tipChatOff: { ru: "Автоперевод в этом чате: ВЫКЛ", en: "Auto-translate in this chat: OFF" },
    tipAutoEnabled: { ru: "Автоперевод включён", en: "Auto Translate Enabled" },
    tipScreen: { ru: "Перевести текст с области экрана", en: "Translate text from a screen area" },
    tipTranslate: { ru: "Перевести", en: "Translate" },
    plateUntranslate: { ru: "Выключить перевод", en: "Turn the translation off" },
    menuCopyOriginal: { ru: "Копировать оригинал", en: "Copy original" },
    menuCopyTranslation: { ru: "Копировать перевод", en: "Copy translation" },
    menuShowOriginal: { ru: "Показать оригинал", en: "Show original" },
    menuShowTranslation: { ru: "Показать перевод", en: "Show translation" },
    transFail: { ru: "Не удалось перевести", en: "Could not translate" },
    nothingToTranslate: { ru: "Здесь нечего переводить", en: "Nothing to translate here" },
    copied: { ru: "Скопировано", en: "Copied" },
    translationCopied: { ru: "Перевод скопирован", en: "Translation copied" },
    tipImageTranslate: { ru: "Перевести текст на этой картинке", en: "Translate the text on this picture" },
    tipImageClose: { ru: "Убрать перевод", en: "Remove the translation" },
    tipFileTranslate: { ru: "Перевести этот файл", en: "Translate this file" },
    tipFileOpen: { ru: "Открыть перевод", en: "Open translation" },
    ariaFileTranslate: { ru: "Перевести файл", en: "Translate file" },
    fileTooBig: { ru: "Файл слишком большой для перевода (больше 10 Кб)", en: "The file is too large to translate (over 10 KB)" },
    fileFail: { ru: "Не удалось перевести файл", en: "Could not translate the file" },
    screenHint: { ru: "Выдели мышью область с текстом. Esc — отмена.", en: "Drag to select the area with text. Esc to cancel." },
    screenWorking: { ru: "Читаю и перевожу...", en: "Reading and translating..." },
    screenDownloading: { ru: "Загружаю данные для распознавания текста (только в первый раз)...", en: "Downloading text recognition data (first time only)..." },
    screenToggleHint: { ru: "Клик — показать оригинал или перевод. Esc — закрыть.", en: "Click to show the original or the translation. Esc to close." },
    screenNoText: { ru: "В выделенной области текст не найден.", en: "No text found in the selected area." },
    screenOcrFail: { ru: "Не удалось прочитать текст с изображения.", en: "Could not read text from the image." },
    textNotFound: { ru: "Текст не найден", en: "Text not found" },
    ocrFail: { ru: "Не удалось распознать текст", en: "Could not recognize the text" },
    replacedHint: { ru: "Переведено. Клик — переключить на оригинал и обратно. {toggle}: переключить всё, {reset}: сбросить, зажать Alt: посмотреть оригинал.", en: "Translated. Click to switch to the original and back. {toggle}: switch all, {reset}: reset, hold Alt: peek at the original." },
    tipHideHint: { ru: "Скрыть эту подсказку: Настройки → Подсказки при наведении", en: "Hide this tip: Settings → Hover tips" },
    editFailSave: { ru: "Не удалось перевести правку — она не сохранена", en: "Could not translate the edit; it was not saved" },
    editFailBox: { ru: "Не удалось сохранить из окошка перевода — нажми Enter в верхнем поле", en: "Could not save from the translation box — press Enter in the upper field" },
    editLowerLabel: { ru: "Переведенный текст сообщения (Изменения тут не влияют на оригинальный текст)", en: "Translated text of the message (changes here do not affect the original text)" },
    editRetranslate: { ru: "перевести заново", en: "translate again" },
    editHintEsc: { ru: "esc для", en: "esc to" },
    editHintCancel: { ru: "отмены", en: "cancel" },
    editHintEnter: { ru: "• enter чтобы", en: "• enter to" },
    editHintSave: { ru: "сохранить", en: "save" },
    editUpperLabel: { ru: "Оригинальный текст сообщения (Внесение изменений переведет текст заново)", en: "Original text of the message (changes will translate the text again)" },
    editFailText: { ru: "Не удалось перевести текст", en: "Could not translate the text" },
    translatorDown: { ru: "Переводчик сейчас не отвечает, попробую позже", en: "The translator is not responding right now; I will try again later" },
    translatorUp: { ru: "Перевод снова работает", en: "Translation works again" },
    translatorFailed: { ru: "Переводчик не ответил: {reason}", en: "The translator did not respond: {reason}" },
    deeplLimit: { ru: "Лимит DeepL исчерпан — перевожу через Google", en: "DeepL limit reached — translating with Google" },
    deeplNoKey: { ru: "Не задан ключ DeepL — переключаюсь на Google", en: "No DeepL key set — switching to Google" },
} as const;

export type TextKey = keyof typeof TEXTS;
